# Generated by Django 5.2 on 2025-06-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
