# Generated by Django 5.2 on 2025-06-17 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0002_package_stripe_price_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seotask',
            old_name='generated_content',
            new_name='optimized_content',
        ),
    ]
