# Generated by Django 5.2 on 2025-06-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0004_blog_blogimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpressconnection',
            name='app_password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wordpressconnection',
            name='username',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
