# Generated by Django 5.2 on 2025-07-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0007_blog_category_keyword_clicks_keyword_impressions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seotask',
            name='task_type',
            field=models.CharField(choices=[('seo_optimization', 'SEO Optimization'), ('blog_writing', 'Blog Writing'), ('keyword_optimization', 'Keyword Optimization')], max_length=50),
        ),
    ]
