# Generated by Django 5.2 on 2025-07-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0008_alter_seotask_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='seo_optimization_limit',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
