# Generated by Django 5.2 on 2025-07-16 17:34

import seo_services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0009_package_seo_optimization_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='seotask',
            name='count_this_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seotask',
            name='month_year',
            field=models.CharField(default=seo_services.models.default_month_year, max_length=7),
        ),
    ]
