# Generated by Django 5.2 on 2025-07-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0010_seotask_count_this_month_seotask_month_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=10),
            preserve_default=False,
        ),
    ]
