# Generated by Django 5.2 on 2025-07-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0011_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='seotask',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
