# Generated by Django 5.2 on 2025-07-20 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0012_seotask_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seotask',
            name='service_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo_tasks', to='seo_services.servicepage'),
        ),
    ]
