# Generated by Django 5.2 on 2025-07-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0013_alter_seotask_service_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslocation',
            name='location_name',
            field=models.CharField(max_length=1000),
        ),
    ]
