# Generated by Django 5.2 on 2025-07-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0014_alter_businesslocation_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslocation',
            name='location_url',
            field=models.URLField(max_length=1000),
        ),
    ]
