# Generated by Django 5.2 on 2025-07-24 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0015_alter_businesslocation_location_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='seo_services.keyword')),
            ],
        ),
    ]
