# Generated by Django 5.2 on 2025-08-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0016_keywordquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='average_position',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
