# Generated by Django 5.2 on 2025-08-13 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0017_keyword_average_position_keyword_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='google_post_limit',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seotask',
            name='task_type',
            field=models.CharField(choices=[('seo_optimization', 'SEO Optimization'), ('blog_writing', 'Blog Writing'), ('keyword_optimization', 'Keyword Optimization'), ('gb_post', 'Google Post')], max_length=50),
        ),
        migrations.CreateModel(
            name='GooglePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seo_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_post', to='seo_services.seotask')),
            ],
        ),
    ]
