# Generated by Django 5.2 on 2025-08-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0018_package_google_post_limit_alter_seotask_task_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seotask',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seotask',
            name='impressions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seotask',
            name='last_metrics_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seotask',
            name='wp_page_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
