# Generated by Django 5.2 on 2025-08-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0019_seotask_clicks_seotask_impressions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='wp_post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
