# Generated by Django 5.2 on 2025-08-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0020_blog_wp_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlepost',
            name='title',
        ),
        migrations.AlterField(
            model_name='googlepost',
            name='area',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seotask',
            name='task_type',
            field=models.CharField(choices=[('seo_optimization', 'SEO Optimization'), ('blog_writing', 'Blog Writing'), ('keyword_optimization', 'Keyword Optimization'), ('gmb_post', 'Google My Business Post')], max_length=50),
        ),
    ]
