# Generated by Django 5.2 on 2025-08-18 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0021_remove_googlepost_title_alter_googlepost_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GMBPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('area', models.CharField(max_length=200)),
                ('keywords', models.JSONField(default=list)),
                ('research_words', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seo_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmb_post', to='seo_services.seotask')),
            ],
        ),
        migrations.DeleteModel(
            name='GooglePost',
        ),
    ]
