# Generated by Django 5.2 on 2025-08-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0022_gmbpost_delete_googlepost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='google_post_limit',
        ),
        migrations.AddField(
            model_name='package',
            name='gmb_post_limit',
            field=models.IntegerField(default=5),
        ),
    ]
