# Generated by Django 5.2 on 2025-08-18 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0023_remove_package_google_post_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmbpost',
            name='seo_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmb_post', to='seo_services.seotask'),
        ),
    ]
