# Generated by Django 5.2 on 2025-08-24 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0024_alter_gmbpost_seo_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='seo_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='seo_services.seotask'),
        ),
    ]
