# Generated by Django 5.2 on 2025-08-25 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0025_alter_blog_seo_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataForSEOKeywordData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_volume', models.PositiveIntegerField(default=0)),
                ('competition', models.FloatField(blank=True, null=True)),
                ('cpc', models.FloatField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('url_found', models.URLField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataforseo_data', to='seo_services.keyword')),
            ],
            options={
                'unique_together': {('keyword',)},
            },
        ),
    ]
