# Generated by Django 5.2 on 2025-08-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0026_dataforseokeyworddata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataforseokeyworddata',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='dataforseokeyworddata',
            name='url_found',
        ),
        migrations.AddField(
            model_name='dataforseokeyworddata',
            name='competition_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataforseokeyworddata',
            name='competition_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dataforseokeyworddata',
            name='high_bid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataforseokeyworddata',
            name='low_bid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
