# Generated by Django 5.2 on 2025-09-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0028_blog_wp_post_url_blog_wp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='job_post_limit',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
