# Generated by Django 5.2 on 2025-09-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0029_package_job_post_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
