# Generated by Django 5.2 on 2025-09-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0031_businessdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslocation',
            name='area_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='businesslocation',
            name='business_service_areas',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='businesslocation',
            name='center',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
