# Generated by Django 5.2 on 2025-09-29 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0032_businesslocation_area_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='area_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='clicks',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='onboarding_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='seo_services.onboardingform'),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
