# Generated by Django 5.2 on 2025-09-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0032_businesslocation_area_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesslocation',
            name='area_list',
        ),
        migrations.RemoveField(
            model_name='businesslocation',
            name='business_service_areas',
        ),
        migrations.RemoveField(
            model_name='businesslocation',
            name='center',
        ),
        migrations.AddField(
            model_name='servicearea',
            name='area_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='business_service_areas',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='center',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
