# Generated by Django 5.2 on 2025-10-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_services', '0033_alter_servicearea_area_name_alter_servicearea_clicks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seotask',
            name='failure_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seotask',
            name='last_failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
