# Generated by Django 5.2 on 2025-09-02 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_matrix', '0003_googlebusinesstoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('sessions', models.IntegerField(default=0)),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('avg_session_duration_minutes', models.FloatField(default=0.0)),
                ('page_views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_summaries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=100)),
                ('users', models.IntegerField(default=0)),
                ('percent', models.FloatField(default=0.0)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='g_matrix.analyticssummary')),
            ],
        ),
        migrations.CreateModel(
            name='RealtimeAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_users', models.IntegerField(default=0)),
                ('summary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realtime', to='g_matrix.analyticssummary')),
            ],
        ),
        migrations.CreateModel(
            name='RealtimeCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('active_users', models.IntegerField(default=0)),
                ('realtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='g_matrix.realtimeanalytics')),
            ],
        ),
        migrations.CreateModel(
            name='RealtimePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=500)),
                ('active_users', models.IntegerField(default=0)),
                ('realtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='g_matrix.realtimeanalytics')),
            ],
        ),
        migrations.CreateModel(
            name='TopCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('users', models.IntegerField(default=0)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_countries', to='g_matrix.analyticssummary')),
            ],
        ),
        migrations.CreateModel(
            name='TopPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=500)),
                ('page_path', models.CharField(max_length=500)),
                ('page_views', models.IntegerField(default=0)),
                ('avg_time_on_page', models.FloatField(default=0.0)),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_pages', to='g_matrix.analyticssummary')),
            ],
        ),
        migrations.CreateModel(
            name='TrafficChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=100)),
                ('users', models.IntegerField(default=0)),
                ('percent', models.FloatField(default=0.0)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_channels', to='g_matrix.analyticssummary')),
            ],
        ),
        migrations.CreateModel(
            name='TrafficTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('users', models.IntegerField(default=0)),
                ('page_views', models.IntegerField(default=0)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_trends', to='g_matrix.analyticssummary')),
            ],
        ),
    ]
