# Generated by Django 5.2 on 2025-09-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g_matrix', '0004_analyticssummary_devicebreakdown_realtimeanalytics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticssummary',
            name='user',
        ),
        migrations.RemoveField(
            model_name='realtimeanalytics',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='trafficchannel',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='traffictrend',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='topcountry',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='toppage',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='realtimepage',
            name='realtime',
        ),
        migrations.RemoveField(
            model_name='realtimecountry',
            name='realtime',
        ),
        migrations.DeleteModel(
            name='DeviceBreakdown',
        ),
        migrations.DeleteModel(
            name='TrafficChannel',
        ),
        migrations.DeleteModel(
            name='TrafficTrend',
        ),
        migrations.DeleteModel(
            name='TopCountry',
        ),
        migrations.DeleteModel(
            name='AnalyticsSummary',
        ),
        migrations.DeleteModel(
            name='TopPage',
        ),
        migrations.DeleteModel(
            name='RealtimePage',
        ),
        migrations.DeleteModel(
            name='RealtimeAnalytics',
        ),
        migrations.DeleteModel(
            name='RealtimeCountry',
        ),
    ]
