# Generated by Django 5.2 on 2025-05-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Learning_points',
            field=models.IntegerField(default=0),
        ),
    ]
