# Generated by Django 5.2 on 2025-05-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_learning_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Learning_points',
        ),
    ]
