# Generated by Django 5.2 on 2025-07-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OnboardingForm',
            new_name='JobOnboardingForm',
        ),
    ]
