# Generated by Django 5.2 on 2025-07-14 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_rename_onboardingform_jobonboardingform'),
        ('seo_services', '0009_package_seo_optimization_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_pages', to=settings.AUTH_USER_MODEL)),
                ('wordpress_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_pages', to='seo_services.wordpressconnection')),
            ],
        ),
    ]
