# Generated by Django 5.2 on 2025-07-16 19:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_jobpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('job_id', models.CharField(max_length=100)),
                ('service_area', models.CharField(max_length=200)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_satisfied', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
