# Generated by Django 5.2 on 2025-08-20 21:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_clientfeedback_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(choices=[('hubspot', 'HubSpot'), ('pipedrive', 'Pipedrive'), ('zoho', 'Zoho CRM'), ('salesforce', 'Salesforce')], max_length=20)),
                ('auth_type', models.CharField(choices=[('oauth', 'OAuth'), ('api_key', 'API Key'), ('both', 'Both')], max_length=10)),
                ('oauth_client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('oauth_client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('oauth_authorize_url', models.URLField(blank=True, null=True)),
                ('oauth_token_url', models.URLField(blank=True, null=True)),
                ('api_key_help_text', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CRMConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(max_length=100)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('api_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('oauth_access_token', models.CharField(blank=True, max_length=500, null=True)),
                ('oauth_refresh_token', models.CharField(blank=True, max_length=500, null=True)),
                ('oauth_token_expiry', models.DateTimeField(blank=True, null=True)),
                ('webhook_secret_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_connections', to=settings.AUTH_USER_MODEL)),
                ('crm_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.crmtype')),
            ],
        ),
    ]
