# Generated by Django 5.2 on 2025-08-20 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_crmtype_crmconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfeedback',
            name='crm_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.crmconnection'),
        ),
    ]
