# Generated by Django 5.2 on 2025-08-22 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_jobtask_jobblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobBlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='job.jobblog')),
            ],
        ),
    ]
