# Generated by Django 5.2 on 2025-08-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_jobblogimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobblog',
            name='wp_post_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
