# Generated by Django 5.2 on 2025-08-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_jobblog_wp_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtask',
            name='task_type',
            field=models.CharField(choices=[('job_blog_writing', 'Job Blog Writing'), ('job_template_generation', 'Job Posting Task'), ('job_gmb_post', 'Job GMB Post')], max_length=50),
        ),
    ]
