# Generated by Django 5.2 on 2025-08-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_alter_jobtask_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobblog',
            name='wp_post_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobblog',
            name='wp_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('publish', 'Published'), ('pending', 'Pending Review'), ('future', 'Scheduled'), ('private', 'Private')], max_length=50, null=True),
        ),
    ]
