# Generated by Django 5.2 on 2025-09-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_jobblog_wp_post_url_jobblog_wp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobonboardingform',
            name='radius',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobonboardingform',
            name='states',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
