# Generated by Django 5.2 on 2025-09-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_jobonboardingform_radius_jobonboardingform_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobonboardingform',
            name='route',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
