# Generated by Django 5.2 on 2025-09-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_jobonboardingform_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobonboardingform',
            name='clean_clearinghouse',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobonboardingform',
            name='clean_drug_test',
            field=models.BooleanField(default=False),
        ),
    ]
