# Generated by Django 5.2 on 2025-09-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_alter_jobonboardingform_clean_clearinghouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobonboardingform',
            name='home_time',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
