# Generated by Django 5.2 on 2025-09-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_jobonboardingform_home_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobonboardingform',
            name='cpm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobonboardingform',
            name='drivers_weekly_earning',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobonboardingform',
            name='drivers_weekly_miles',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
