# Generated by Django 5.2 on 2025-09-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_alter_jobonboardingform_cpm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobonboardingform',
            name='earning_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
