# Generated by Django 5.2 on 2025-09-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0020_jobonboardingform_earning_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobonboardingform',
            name='driver_percentage',
            field=models.CharField(blank=True, help_text='If applicable', max_length=100, null=True),
        ),
    ]
