# Generated by Django 5.2 on 2025-09-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_alter_jobonboardingform_driver_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobblog',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobblog',
            name='ctr',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='jobblog',
            name='impressions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobblog',
            name='last_metrics_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobblog',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='ctr',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='impressions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='last_metrics_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='wp_page_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
