# Generated by Django 5.2 on 2025-09-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0022_jobblog_clicks_jobblog_ctr_jobblog_impressions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobblog',
            name='ga4_avg_time_on_page',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='jobblog',
            name='ga4_bounce_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='jobblog',
            name='ga4_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobblog',
            name='ga4_page_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='ga4_avg_time_on_page',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='ga4_bounce_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='ga4_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='ga4_page_views',
            field=models.IntegerField(default=0),
        ),
    ]
