# Generated by Django 5.2 on 2025-09-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0023_jobblog_ga4_avg_time_on_page_jobblog_ga4_bounce_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobonboardingform',
            name='company_service_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percent for Owner Operator only', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='jobonboardingform',
            name='down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobonboardingform',
            name='ifta_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='jobonboardingform',
            name='insurance_liability_cargo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='jobonboardingform',
            name='insurance_physical_damage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='jobonboardingform',
            name='service_fee_includes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='jobonboardingform',
            name='tablet_cost',
            field=models.CharField(blank=True, help_text="Either number or 'driver'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobonboardingform',
            name='trailer_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='jobonboardingform',
            name='truck_lease_weekly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
