# Generated by Django 5.2 on 2025-09-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0024_jobonboardingform_company_service_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobonboardingform',
            name='rent_trailers_to_drivers',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
