# Generated by Django 5.2 on 2025-09-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0025_jobonboardingform_rent_trailers_to_drivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobonboardingform',
            name='driver_provided_tablet',
            field=models.BooleanField(default=False),
        ),
    ]
