# Generated by Django 5.2 on 2025-09-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0026_jobonboardingform_driver_provided_tablet'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobonboardingform',
            name='tolls_fuel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
