# Generated by Django 5.2 on 2025-09-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0028_oauthstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfeedback',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
