# Generated by Django 5.2 on 2025-09-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0029_clientfeedback_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmconnection',
            name='processed_deals',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
