# Generated by Django 5.2 on 2025-09-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0030_crmconnection_processed_deals'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobonboardingform',
            name='pay_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
