# Generated by Django 5.2 on 2025-09-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0031_jobonboardingform_pay_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobonboardingform',
            name='down_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobonboardingform',
            name='down_payment',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobonboardingform',
            name='earning_type',
            field=models.BooleanField(blank=True, max_length=50, null=True),
        ),
    ]
