# Generated by Django 5.2 on 2025-09-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0032_jobonboardingform_down_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobonboardingform',
            name='earning_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
