# Generated by Django 5.2 on 2025-09-08 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0033_alter_jobonboardingform_earning_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobBlogKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('clicks', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('ctr', models.FloatField(default=0)),
                ('average_position', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('job_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='job.jobblog')),
            ],
            options={
                'unique_together': {('job_blog', 'keyword')},
            },
        ),
    ]
