# Generated by Django 5.2 on 2025-09-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0035_alter_jobonboardingform_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobonboardingform',
            name='wp_page_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
