# Generated by Django 5.2 on 2025-09-16 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0036_jobonboardingform_wp_page_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobonboardingform',
            name='wp_page_url',
        ),
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_request_payload', models.JSONField(blank=True, default=dict, null=True)),
                ('ai_response_payload', models.JSONField(blank=True, default=dict, null=True)),
                ('generated_content', models.TextField(blank=True, null=True)),
                ('wp_page_id', models.IntegerField(blank=True, null=True)),
                ('wp_page_url', models.URLField(blank=True, null=True)),
                ('wp_page_slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('wp_post_data', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='job.jobonboardingform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
