# Generated by Django 5.2 on 2025-09-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0037_remove_jobonboardingform_wp_page_url_jobtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmconnection',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
