# Generated by Django 5.2 on 2025-09-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0037_remove_jobonboardingform_wp_page_url_jobtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobonboardingform',
            name='wordpress_page_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobonboardingform',
            name='wordpress_post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
