# Generated by Django 5.2 on 2025-09-16 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0038_crmconnection_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackFormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction_level', models.CharField(choices=[('very_dissatisfied', 'Very Dissatisfied'), ('dissatisfied', 'Dissatisfied'), ('neutral', 'Neutral'), ('satisfied', 'Satisfied'), ('very_satisfied', 'Very Satisfied')], max_length=20)),
                ('issues_faced', models.TextField(blank=True, null=True)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('would_recommend', models.BooleanField(null=True)),
                ('contact_permission', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to='job.clientfeedback')),
            ],
        ),
    ]
