# Generated by Django 5.2 on 2025-09-17 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0038_jobonboardingform_wordpress_page_url_and_more'),
        ('job', '0039_feedbackformresponse'),
    ]

    operations = [
    ]
