# Generated by Django 5.2 on 2025-09-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0039_feedbackformresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmtype',
            name='provider',
            field=models.CharField(choices=[('hubspot', 'HubSpot'), ('pipedrive', 'Pipedrive'), ('zoho', 'Zoho CRM'), ('salesforce', 'Salesforce'), ('jobber', 'Jobber CRM')], max_length=20),
        ),
    ]
