# Generated by Django 5.2 on 2025-09-24 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0040_alter_crmtype_provider'),
        ('job', '0040_merge_20250917_1559'),
    ]

    operations = [
    ]
