# Generated by Django 5.2 on 2025-09-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0041_merge_20250917_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmtype',
            name='provider',
            field=models.CharField(choices=[('hubspot', 'HubSpot'), ('pipedrive', 'Pipedrive'), ('zoho', 'Zoho CRM'), ('salesforce', 'Salesforce'), ('jobber', 'Jobber CRM'), ('zendesk', 'Zendesk')], max_length=20),
        ),
    ]
