# Generated by Django 5.2 on 2025-09-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0041_merge_20250917_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthstate',
            name='code_verifier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
