# Generated by Django 5.2 on 2025-09-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0041_merge_20250924_2204'),
        ('job', '0042_alter_crmtype_provider'),
    ]

    operations = [
    ]
