# Generated by Django 5.2 on 2025-09-26 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0042_oauthstate_code_verifier'),
        ('job', '0043_merge_20250925_1248'),
    ]

    operations = [
    ]
