# Generated by Django 5.2 on 2025-09-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0044_merge_20250929_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfeedback',
            name='feedback_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='oauthstate',
            name='code_verifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
