# Generated by Django 5.2 on 2025-09-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0044_merge_20250926_2045'),
        ('job', '0045_clientfeedback_feedback_submitted_and_more'),
    ]

    operations = [
    ]
