# Generated by Django 5.2 on 2025-10-08 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0047_customer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='job_customer',
        ),
    ]
