# Generated by Django 5.2 on 2025-10-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0048_alter_customer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
