# Generated by Django 5.2 on 2025-10-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0051_remove_customer_file_name_remove_customer_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobonboardingform',
            name='company_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobonboardingform',
            name='funding_statement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobonboardingform',
            name='has_safety',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobonboardingform',
            name='phd_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='jobonboardingform',
            name='safety_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobonboardingform',
            name='years_in_operation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
