# Generated by Django 5.2 on 2025-10-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0052_jobonboardingform_company_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobonboardingform',
            name='manual_earnings_max',
            field=models.CharField(blank=True, help_text='Maximum weekly earnings (% of gross)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobonboardingform',
            name='manual_earnings_min',
            field=models.CharField(blank=True, help_text='Minimum weekly earnings (% of gross)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobonboardingform',
            name='weekly_miles_max',
            field=models.CharField(blank=True, help_text='Maximum weekly miles', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobonboardingform',
            name='weekly_miles_min',
            field=models.CharField(blank=True, help_text='Minimum weekly miles', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobonboardingform',
            name='down_payment',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
