# Generated by Django 5.2 on 2025-10-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0053_jobonboardingform_manual_earnings_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobonboardingform',
            name='pay_structure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobonboardingform',
            name='pay_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
